In [12]:
import numpy as np
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

mon_tab_bi=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_tab_bi)

print(mon_tab_bi[0][2]) # 1ere ligne 3ieme colonne
print(mon_tab_bi[0, 2]) # ligne colonne

print(mon_tab_bi[:, 0]) # toute 1ere colonne
print(mon_tab_bi[0, :]) # toute 1ere ligne

# mon_tab_bi[0,0]='texte'
mon_tab_bi[0,0]=0.2 # prend que la partie entière
print(mon_tab_bi[0, :])

mon_tab_bi.dtype # int64

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[1 4 7]
[1 2 3]
[0 2 3]


dtype('int64')

In [14]:
mon_tab_bi_F=np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]],dtype='float32')
print(mon_tab_bi_F)
mon_tab_bi_F.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float32')

In [17]:
mon_array_zero=np.zeros((4,6),dtype='int64')
print(mon_array_zero)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
mon_array_ones=np.ones((4,6),dtype='int32')
print(mon_array_ones)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [20]:
mon_array_random=np.random.random((4,6))
print(mon_array_random)

[[0.90448651 0.42882299 0.21378614 0.62657103 0.54913723 0.28481089]
 [0.37564733 0.24632236 0.47269873 0.07110194 0.98318115 0.25358992]
 [0.21156276 0.16112308 0.75089006 0.13412543 0.22643423 0.21923714]
 [0.03254535 0.40920546 0.27322146 0.28792067 0.27200896 0.90617924]]


In [131]:
iris=np.genfromtxt("iris.csv",delimiter=';',skip_header=True,encoding='latin-1')
print(iris)
print(iris.dtype)
type(iris)

# espèce 1: Setosa
# espèce 2: Versicolor
# espèce 3: Virginica

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

numpy.ndarray

In [132]:
# sauve les données après W dessus
# np.savetxt("iris2.csv",donnees_iris,delimiter=';')

# indexation simple
iris[2,1] # affiche 3.2, ligne=3 col=2

# modif
iris[2,1]=4
print(iris[2,1])

iris[2,1]=3.2

4.0


In [35]:
# donne le rep de jupyter
%pwd

'/home/simplon'

In [36]:
%ls

 4._Exercice_premier_pas_avec_python.ipynb   iris.csv
 anaconda3/                                  Modèles/
 Bureau/                                     Musique/
 CH8_APP3.ipynb                             'NumPy exemples cours.ipynb'
'Cours tuples, dicos, fonction.ipynb'        Pendu.ipynb
 Documents/                                  Public/
 examples.desktop                           'Python support 2.ipynb'
'Exos python 2.ipynb'                        snap/
 Images/                                     Téléchargements/
 iris2.csv                                   Vidéos/


In [133]:
iris[iris>2] # prend toutes les valeurs >2

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [134]:
# compte les données >2
iris[iris>2].shape
# peut mettre [0]

(472,)

In [135]:
iris>2 # met True si >2

array([[ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False, Fal

In [136]:
# ligne où premier >5
iris[donnees_iris[:,0]>5]

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4.2, 1.4, 0.2, 1. ],
       [5.5, 3.5, 1.3, 0.2, 1. ],
       [5.1, 3.4, 1.5, 0.2, 1. ],
       [5.1, 3.8, 1.9, 0.4, 1. ],
       [5.1, 3.8, 1.6, 0.2, 1. ],
       [5.3, 3.7, 1.5, 0.2, 1. ],
       [7. , 3.2, 4.7, 1.4, 2. ],
       [6.4, 3.2, 4.5, 1.5, 2. ],
       [6.9, 3.1, 4.9, 1.5, 2. ],
       [5.5, 2.3, 4. , 1.3, 2. ],
       [6.5, 2.8, 4.6, 1.5, 2. ],
       [5.7, 2.8, 4.5, 1.3, 2. ],
       [6.3, 3.3, 4.7, 1.6, 2. ],
       [6.6, 2

In [137]:
iris[donnees_iris[:,3]>3] # 0

array([], shape=(0, 5), dtype=float64)

In [138]:
notre_tableau2=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9,
                         10.1,1.11,1.12,1.13,1.14,1.15,1.16,1.17,1.18,1.19,20.1])
print("Notre tab:")
print(notre_tableau2)

print("Fancy indexing:") # juste une vue...
indices=np.array([[4,10,5],[12,8,9],[0,9,19]])
print(notre_tableau2[indices])

Notre tab:
[ 1.1   2.2   3.3   4.4   5.5   6.6   7.7   8.8   9.9  10.1   1.11  1.12
  1.13  1.14  1.15  1.16  1.17  1.18  1.19 20.1 ]
Fancy indexing:
[[ 5.5   1.11  6.6 ]
 [ 1.13  9.9  10.1 ]
 [ 1.1  10.1  20.1 ]]


In [139]:
# slices
print(notre_tableau2[:3]) #  début et 3 premiers elem
print(notre_tableau2[10:]) # 10 derniers
print(notre_tableau2[3:7]) # plage
print(notre_tableau2[3:7:2]) # pas 2

[1.1 2.2 3.3]
[ 1.11  1.12  1.13  1.14  1.15  1.16  1.17  1.18  1.19 20.1 ]
[4.4 5.5 6.6 7.7]
[4.4 6.6]


In [140]:
# select 2 premiere ligne de la 4 colonne
iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [141]:
iris[-1,:] # derniere ligne

array([5.9, 3. , 5.1, 1.8, 3. ])

In [142]:
sous_tab=notre_tableau[:5] # 5 premieres valeurs de notre_tableau MAIS vue
sous_tab

array([1, 2, 3, 4, 5])

In [143]:
sous_tab[0]=10

In [144]:
sous_tab

array([10,  2,  3,  4,  5])

In [145]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [146]:
# copy des données
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
sous_tab=notre_tableau[:5].copy()
sous_tab[0]=10
print(notre_tableau)
print(sous_tab)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[10  2  3  4  5]


In [147]:
import numpy as np
mon_tableau=np.array([[1,2,3],[10,11,12],[21,22,23]])
print(mon_tableau)
t=np.add(mon_tableau,10)
print(mon_tableau)
print(t)

t2=np.multiply(mon_tableau,20)
print(t2)

mon_tableau2=np.array([10,20,30])
t3=np.subtract(mon_tableau,mon_tableau2)
print("=====================================================")
print(mon_tableau)
print(mon_tableau2)
print(t3)

[[ 1  2  3]
 [10 11 12]
 [21 22 23]]
[[ 1  2  3]
 [10 11 12]
 [21 22 23]]
[[11 12 13]
 [20 21 22]
 [31 32 33]]
[[ 20  40  60]
 [200 220 240]
 [420 440 460]]
[[ 1  2  3]
 [10 11 12]
 [21 22 23]]
[10 20 30]
[[ -9 -18 -27]
 [  0  -9 -18]
 [ 11   2  -7]]


In [148]:
mon_tableau3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_tableau3)
t4=np.multiply(mon_tableau,mon_tableau3)
print(t4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   4   9]
 [ 40  55  72]
 [147 176 207]]


In [149]:
# somme toutes les données
print(np.sum(donnees_iris))

# somme colonne
print(np.sum(donnees_iris,axis=0))

# somme /ligne
print(np.sum(donnees_iris,axis=1))

2378.7
[876.5 458.6 563.7 179.9 300. ]
[11.2 10.5 10.4 10.4 11.2 12.4 10.7 11.1  9.9 10.6 11.8 11.  10.3  9.5
 12.2 13.  12.  11.3 12.5 11.7 11.7 11.7 10.4 11.6 11.3 10.8 11.4 11.4
 11.2 10.7 10.7 11.7 11.9 12.3 10.7 10.6 11.5 11.   9.9 11.2 11.1  9.4
 10.1 11.7 12.2 10.5 11.7 10.4 11.7 10.9 18.3 17.6 18.4 15.1 17.4 16.3
 17.9 13.6 17.4 15.2 13.5 16.6 15.2 17.1 15.4 17.6 16.6 15.6 16.4 15.1
 17.7 16.2 17.2 16.8 16.9 17.4 17.8 18.4 16.9 14.8 14.8 14.6 15.6 17.4
 16.4 17.5 18.  16.3 16.  15.3 15.7 17.1 15.6 13.6 15.8 16.1 16.1 16.7
 13.7 15.9 21.1 18.5 21.1 19.6 20.5 22.3 16.6 21.3 19.8 22.4 19.8 19.3
 20.4 18.2 19.1 20.2 19.8 23.4 22.5 17.7 21.1 18.3 22.2 18.7 20.8 21.2
 18.6 18.8 19.9 20.6 21.2 23.1 20.  18.7 18.7 22.1 20.7 19.8 18.6 20.5
 20.8 20.4 18.5 21.2 21.2 20.2 18.7 19.7 20.3 18.8]


In [150]:
print(np.mean(iris,axis=0)) # moyenne
print(np.std(iris,axis=0)) # varience
print(np.max(iris,axis=0)) # max
print(np.min(iris,axis=0)) # min

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[0.82530129 0.43441097 1.75940407 0.75969263 0.81649658]
[7.9 4.4 6.9 2.5 3. ]
[4.3 2.  1.  0.1 1. ]


In [151]:
iris[iris[:,4]==3] # vue avec type 3 Virginica
moy_iris3=np.mean(iris[donnees_iris[:,4]==3],axis=0)
moy_iris1=np.mean(iris[donnees_iris[:,4]==1],axis=0)
moy_iris2=np.mean(iris[donnees_iris[:,4]==2],axis=0)
print(moy_iris3) # moyenne des données pour les Virginica
print(moy_iris2) # moyenne des données pour la variété 2
print(moy_iris1) # moyenne des données pour la variété 1

[6.588 2.974 5.552 2.026 3.   ]
[5.936 2.77  4.26  1.326 2.   ]
[5.006 3.428 1.462 0.246 1.   ]


In [152]:
print(iris.size)
print(iris.shape)
print(iris.ndim)
print(iris.dtype)

750
(150, 5)
2
float64


In [153]:
# transposé passer les colonnes en lignes et inversement
print(iris.T)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2.6 3.  2.

In [154]:
np.append(notre_tableau,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [155]:
np.append(iris,[[10,10,10,10,10]],axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,  0.2,  1. ],
       [ 5. ,  3. ,  1.6,

In [156]:
t=np.insert(notre_tableau,1,42)
print(notre_tableau)
print(t)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1 42  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [157]:
np.insert(iris,1,[10,10,10,10,10],axis=0)

array([[ 5.1,  3.5,  1.4,  0.2,  1. ],
       [10. , 10. , 10. , 10. , 10. ],
       [ 4.9,  3. ,  1.4,  0.2,  1. ],
       [ 4.7,  3.2,  1.3,  0.2,  1. ],
       [ 4.6,  3.1,  1.5,  0.2,  1. ],
       [ 5. ,  3.6,  1.4,  0.2,  1. ],
       [ 5.4,  3.9,  1.7,  0.4,  1. ],
       [ 4.6,  3.4,  1.4,  0.3,  1. ],
       [ 5. ,  3.4,  1.5,  0.2,  1. ],
       [ 4.4,  2.9,  1.4,  0.2,  1. ],
       [ 4.9,  3.1,  1.5,  0.1,  1. ],
       [ 5.4,  3.7,  1.5,  0.2,  1. ],
       [ 4.8,  3.4,  1.6,  0.2,  1. ],
       [ 4.8,  3. ,  1.4,  0.1,  1. ],
       [ 4.3,  3. ,  1.1,  0.1,  1. ],
       [ 5.8,  4. ,  1.2,  0.2,  1. ],
       [ 5.7,  4.4,  1.5,  0.4,  1. ],
       [ 5.4,  3.9,  1.3,  0.4,  1. ],
       [ 5.1,  3.5,  1.4,  0.3,  1. ],
       [ 5.7,  3.8,  1.7,  0.3,  1. ],
       [ 5.1,  3.8,  1.5,  0.3,  1. ],
       [ 5.4,  3.4,  1.7,  0.2,  1. ],
       [ 5.1,  3.7,  1.5,  0.4,  1. ],
       [ 4.6,  3.6,  1. ,  0.2,  1. ],
       [ 5.1,  3.3,  1.7,  0.5,  1. ],
       [ 4.8,  3.4,  1.9,

In [158]:
np.delete(iris,1,axis=1) # supprime la colonne 2

array([[5.1, 1.4, 0.2, 1. ],
       [4.9, 1.4, 0.2, 1. ],
       [4.7, 1.3, 0.2, 1. ],
       [4.6, 1.5, 0.2, 1. ],
       [5. , 1.4, 0.2, 1. ],
       [5.4, 1.7, 0.4, 1. ],
       [4.6, 1.4, 0.3, 1. ],
       [5. , 1.5, 0.2, 1. ],
       [4.4, 1.4, 0.2, 1. ],
       [4.9, 1.5, 0.1, 1. ],
       [5.4, 1.5, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [4.8, 1.4, 0.1, 1. ],
       [4.3, 1.1, 0.1, 1. ],
       [5.8, 1.2, 0.2, 1. ],
       [5.7, 1.5, 0.4, 1. ],
       [5.4, 1.3, 0.4, 1. ],
       [5.1, 1.4, 0.3, 1. ],
       [5.7, 1.7, 0.3, 1. ],
       [5.1, 1.5, 0.3, 1. ],
       [5.4, 1.7, 0.2, 1. ],
       [5.1, 1.5, 0.4, 1. ],
       [4.6, 1. , 0.2, 1. ],
       [5.1, 1.7, 0.5, 1. ],
       [4.8, 1.9, 0.2, 1. ],
       [5. , 1.6, 0.2, 1. ],
       [5. , 1.6, 0.4, 1. ],
       [5.2, 1.5, 0.2, 1. ],
       [5.2, 1.4, 0.2, 1. ],
       [4.7, 1.6, 0.2, 1. ],
       [4.8, 1.6, 0.2, 1. ],
       [5.4, 1.5, 0.4, 1. ],
       [5.2, 1.5, 0.1, 1. ],
       [5.5, 1.4, 0.2, 1. ],
       [4.9, 1

In [159]:
np.delete(iris,[1,2,3,4],axis=0) # supprime les lignes 2, 3, 4 et 5

array([[5.1, 3.5, 1.4, 0.2, 1. ],
       [5.4, 3.9, 1.7, 0.4, 1. ],
       [4.6, 3.4, 1.4, 0.3, 1. ],
       [5. , 3.4, 1.5, 0.2, 1. ],
       [4.4, 2.9, 1.4, 0.2, 1. ],
       [4.9, 3.1, 1.5, 0.1, 1. ],
       [5.4, 3.7, 1.5, 0.2, 1. ],
       [4.8, 3.4, 1.6, 0.2, 1. ],
       [4.8, 3. , 1.4, 0.1, 1. ],
       [4.3, 3. , 1.1, 0.1, 1. ],
       [5.8, 4. , 1.2, 0.2, 1. ],
       [5.7, 4.4, 1.5, 0.4, 1. ],
       [5.4, 3.9, 1.3, 0.4, 1. ],
       [5.1, 3.5, 1.4, 0.3, 1. ],
       [5.7, 3.8, 1.7, 0.3, 1. ],
       [5.1, 3.8, 1.5, 0.3, 1. ],
       [5.4, 3.4, 1.7, 0.2, 1. ],
       [5.1, 3.7, 1.5, 0.4, 1. ],
       [4.6, 3.6, 1. , 0.2, 1. ],
       [5.1, 3.3, 1.7, 0.5, 1. ],
       [4.8, 3.4, 1.9, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [5. , 3.4, 1.6, 0.4, 1. ],
       [5.2, 3.5, 1.5, 0.2, 1. ],
       [5.2, 3.4, 1.4, 0.2, 1. ],
       [4.7, 3.2, 1.6, 0.2, 1. ],
       [4.8, 3.1, 1.6, 0.2, 1. ],
       [5.4, 3.4, 1.5, 0.4, 1. ],
       [5.2, 4.1, 1.5, 0.1, 1. ],
       [5.5, 4

In [160]:
print(iris)

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.2 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.6 1.4 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

In [161]:
np.delete(notre_tableau,1) # supprime le 2ieme elem de la vue

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [162]:
print(notre_tableau)
notre_tableau1,notre_tableau2,notre_tableau3=np.split(notre_tableau,[2,6])
print(notre_tableau1,notre_tableau2,notre_tableau3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [163]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print(array)
array1,array2=np.vsplit(array,[2])
print("array 1:",array1)
print("array 2 :",array2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array 1: [[1. 2. 3.]
 [4. 5. 6.]]
array 2 : [[7. 8. 9.]]


In [164]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print(array)
array1,array2=np.hsplit(array,[2])
print("array 1:",array1)
print("array 2 :",array2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array 1: [[1. 2.]
 [4. 5.]
 [7. 8.]]
array 2 : [[3.]
 [6.]
 [9.]]


In [165]:
t1,t2,t3=np.array([1,2,3,4,5]),np.array([6,7,8,9]),np.array([10,11,12])
t=np.concatenate([t1,t2,t3])
print("concat: ",t)

concat:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [167]:
t1=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
t2=np.array([[10,11,12],[13,14,15],[16,17,18]],dtype="float")
t=np.concatenate([t1,t2]) # fonctionne avec autant de t
print(t)

# vstack() hstack() concatene une ligne ou une colonne

# * fait juste le carre
# mat produit matriciel

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [168]:
# print(iris)
# np.delete(iris,[4],axis=1) # delete la derniere colonne
# np.mean(np.delete(iris,[4],axis=1),axis=1) # moyenne
# iris[iris[:,4]==3] # vue avec type 3 Virginica

iris_mean = np.mean(iris[:,:4], axis=1)
print(iris_mean)
print(np.insert(iris, 5,iris_mean, axis=1))

[2.55  2.375 2.35  2.35  2.55  2.85  2.425 2.525 2.225 2.4   2.7   2.5
 2.325 2.125 2.8   3.    2.75  2.575 2.875 2.675 2.675 2.675 2.35  2.65
 2.575 2.45  2.6   2.6   2.55  2.425 2.425 2.675 2.725 2.825 2.425 2.4
 2.625 2.5   2.225 2.55  2.525 2.1   2.275 2.675 2.8   2.375 2.675 2.35
 2.675 2.475 4.075 3.9   4.1   3.275 3.85  3.575 3.975 2.9   3.85  3.3
 2.875 3.65  3.3   3.775 3.35  3.9   3.65  3.4   3.6   3.275 3.925 3.55
 3.8   3.7   3.725 3.85  3.95  4.1   3.725 3.2   3.2   3.15  3.4   3.85
 3.6   3.875 4.    3.575 3.5   3.325 3.425 3.775 3.4   2.9   3.45  3.525
 3.525 3.675 2.925 3.475 4.525 3.875 4.525 4.15  4.375 4.825 3.4   4.575
 4.2   4.85  4.2   4.075 4.35  3.8   4.025 4.3   4.2   5.1   4.875 3.675
 4.525 3.825 4.8   3.925 4.45  4.55  3.9   3.95  4.225 4.4   4.55  5.025
 4.25  3.925 3.925 4.775 4.425 4.2   3.9   4.375 4.45  4.35  3.875 4.55
 4.55  4.3   3.925 4.175 4.325 3.95 ]
[[5.1   3.5   1.4   0.2   1.    2.55 ]
 [4.9   3.    1.4   0.2   1.    2.375]
 [4.7   3.2   1.3  

In [170]:
# ajouter une ligne avec moy colonne
iris_mean = np.mean(iris, axis=0)
print(iris_mean)
# print(np.concatenate([donnees_iris,iris_mean]))


moyenne = np.mean(iris, axis = 0)
print(np.insert(iris, iris.shape[0], moyenne, axis = 0 ))

[5.84333333 3.05733333 3.758      1.19933333 2.        ]
[[5.1        3.5        1.4        0.2        1.        ]
 [4.9        3.         1.4        0.2        1.        ]
 [4.7        3.2        1.3        0.2        1.        ]
 [4.6        3.1        1.5        0.2        1.        ]
 [5.         3.6        1.4        0.2        1.        ]
 [5.4        3.9        1.7        0.4        1.        ]
 [4.6        3.4        1.4        0.3        1.        ]
 [5.         3.4        1.5        0.2        1.        ]
 [4.4        2.9        1.4        0.2        1.        ]
 [4.9        3.1        1.5        0.1        1.        ]
 [5.4        3.7        1.5        0.2        1.        ]
 [4.8        3.4        1.6        0.2        1.        ]
 [4.8        3.         1.4        0.1        1.        ]
 [4.3        3.         1.1        0.1        1.        ]
 [5.8        4.         1.2        0.2        1.        ]
 [5.7        4.4        1.5        0.4        1.        ]
 [5.4        3.